apiVersion: v1
kind: Service
metadata:
  name: portal
  namespace: ibm-bank
  labels:
    app: portal
    service: portal
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: portal
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-app
  namespace: ibm-bank
  labels:
    app: portal
    version: v0.3
spec:
  selector:
    matchLabels:
      app: portal
  replicas: 2
  template:
    metadata:
      labels:
        app: portal
        version: v0.3
    spec:
      containers:
        - name: portal
          image: src32/ibm-bank-portal:v0.3
          imagePullPolicy: Always
          ports:
            - containerPort: 9080
      imagePullSecrets:
        - name: tonyfieit75-pull-secret
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portal-ingress
  namespace: ibm-bank
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: ibm-bank.detera.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portal
                port:
                  number: 9080
